version: '3'

services:
  php:
    build:
      dockerfile: deploy/php/Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ./:/app

  nginx:
    build:
      dockerfile: deploy/nginx/Dockerfile
      context: .
    ports:
      - 8080:80
    volumes:
      - ./public:/app/public
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/
    depends_on:
      - php
    restart: unless-stopped
